analyzer:
  errors:
    avoid_js_rounded_ints: ignore
    cascade_invocations: ignore
    strict_raw_type: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
