name: habit_quest
description: Your journey to habit mastery begins here
version: 1.0.0+108
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  page_transition: ^2.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13  
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
