name: habit_quest
description: Your journey to habit mastery begins here
version: 1.0.0+111
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  audioplayers: ^6.1.0
  bloc: ^8.1.4
  cloud_firestore: ^5.6.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.10.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  google_sign_in: ^6.2.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  line_awesome_flutter: ^3.0.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  page_transition: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.4

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13  
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  objectbox_generator: ^4.0.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/hooray.mp3
    - assets/success.mp3
    - .env
