// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXPD4F6SqRAELptvdMRB0TIPUHQ8_igsU',
    appId: '1:61930010960:web:f2d635694f27836890d455',
    messagingSenderId: '61930010960',
    projectId: 'habitquest-aa973',
    authDomain: 'habitquest-aa973.firebaseapp.com',
    storageBucket: 'habitquest-aa973.firebasestorage.app',
    measurementId: 'G-RS8C1K346Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATDHj3XGBGon9tzdpcGrjUFWoejF8rsDI',
    appId: '1:61930010960:android:caf4688aaa35daed90d455',
    messagingSenderId: '61930010960',
    projectId: 'habitquest-aa973',
    storageBucket: 'habitquest-aa973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBClmoKlFP1HTpigWr5_PtQEYM2esXS-MQ',
    appId: '1:61930010960:ios:e36466ed8e32468e90d455',
    messagingSenderId: '61930010960',
    projectId: 'habitquest-aa973',
    storageBucket: 'habitquest-aa973.firebasestorage.app',
    iosBundleId: 'com.example.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBClmoKlFP1HTpigWr5_PtQEYM2esXS-MQ',
    appId: '1:61930010960:ios:149ed39c1ff0081190d455',
    messagingSenderId: '61930010960',
    projectId: 'habitquest-aa973',
    storageBucket: 'habitquest-aa973.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXPD4F6SqRAELptvdMRB0TIPUHQ8_igsU',
    appId: '1:61930010960:web:eb43bbfea2e357aa90d455',
    messagingSenderId: '61930010960',
    projectId: 'habitquest-aa973',
    authDomain: 'habitquest-aa973.firebaseapp.com',
    storageBucket: 'habitquest-aa973.firebasestorage.app',
    measurementId: 'G-6TTCZNLBJ1',
  );
}
